const namesData = [
    // A
    { name: "Abdulkadir", gender: "Erkek", origin: "Arapça", syllables: 4, length: 10, meaning: "Güç ve kudret sahibi" },
    { name: "Acelya", gender: "Kız", origin: "Latince", syllables: 3, length: 6, meaning: "Açelya çiçeği" },
    { name: "Ada", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 3, meaning: "Dört tarafı sularla çevrili kara parçası" },
    { name: "Adem", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "İlk insan, adam" },
    { name: "Adnan", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Cennetin orta yerinde bulunan yer" },
    { name: "Afra", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Ayın 13. gecesi, beyaz toprak" },
    { name: "Ahmet", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Çok övülmüş, beğenilmiş" },
    { name: "Ahu", gender: "Kız", origin: "Farsça", syllables: 2, length: 3, meaning: "Ceylan, karaca, güzel gözlü" },
    { name: "Akın", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Hücum, saldırı" },
    { name: "Alara", gender: "Kız", origin: "Türkçe", syllables: 3, length: 5, meaning: "Su perisi" },
    { name: "Alev", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Ateşin çıkardığı ışık ve ısı" },
    { name: "Aleyna", gender: "Kız", origin: "Arapça", syllables: 3, length: 6, meaning: "Üstün, yüce" },
    { name: "Ali", gender: "Erkek", origin: "Arapça", syllables: 2, length: 3, meaning: "Yüce, ulu" },
    { name: "Almıla", gender: "Kız", origin: "Türkçe", syllables: 3, length: 6, meaning: "Elma gibi güzel" },
    { name: "Alp", gender: "Erkek", origin: "Türkçe", syllables: 1, length: 3, meaning: "Yiğit, kahraman" },
    { name: "Alparslan", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 9, meaning: "Yiğit aslan" },
    { name: "Alper", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Yiğit asker" },
    { name: "Alperen", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 7, meaning: "Yiğitlerin yiğidi" },
    { name: "Altan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Altın gibi değerli, kırmızı tan" },
    { name: "Altay", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Yüksek dağ, orman" },
    { name: "Amine", gender: "Kız", origin: "Arapça", syllables: 3, length: 5, meaning: "Güvenilir, emin" },
    { name: "Aras", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Doğu Anadolu'da bir nehir" },
    { name: "Arda", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Hükümdar asası, işaret çubuğu" },
    { name: "Arif", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Bilen, bilgili, irfan sahibi" },
    { name: "Arzu", gender: "Kız", origin: "Farsça", syllables: 2, length: 4, meaning: "İstek, hasret" },
    { name: "Asel", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Bal, cennet balı" },
    { name: "Aslı", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Öz, köken, temel" },
    { name: "Aslıhan", gender: "Kız", origin: "Türkçe", syllables: 3, length: 7, meaning: "Asil hanım" },
    { name: "Asmin", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Gök, sema" },
    { name: "Asya", gender: "Kız", origin: "Yunanca", syllables: 2, length: 4, meaning: "Dünyanın en büyük kıtası" },
    { name: "Ata", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 3, meaning: "Baba, dede, yaşlı kişi" },
    { name: "Atakan", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 6, meaning: "Atasının kanını taşıyan" },
    { name: "Atalay", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 6, meaning: "Ata gibi ay" },
    { name: "Atilla", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 6, meaning: "Atalık, babalık" },
    { name: "Atlas", gender: "Erkek", origin: "Yunanca", syllables: 2, length: 5, meaning: "Dünya haritası, mitolojik kahraman" },
    { name: "Ayaz", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Soğuk ve durgun hava" },
    { name: "Aybike", gender: "Kız", origin: "Türkçe", syllables: 3, length: 6, meaning: "Ay gibi güzel kadın" },
    { name: "Ayça", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Hilal, ayın ilk hali" },
    { name: "Aydın", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Işıklı, parlak, bilgili" },
    { name: "Aylin", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ayın çevresindeki ışık halkası" },
    { name: "Aysel", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ay gibi parlak, sel gibi coşkulu" },
    { name: "Ayşe", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Rahat ve huzurlu yaşayan" },
    { name: "Ayşegül", gender: "Kız", origin: "Farsça", syllables: 3, length: 7, meaning: "Gül gibi güzel ve neşeli" },
    { name: "Azra", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "El değmemiş, bakire" },

    // B
    { name: "Baha", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Değer, kıymet" },
    { name: "Bahadır", gender: "Erkek", origin: "Farsça", syllables: 3, length: 7, meaning: "Yiğit, kahraman" },
    { name: "Bahar", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Yazla kış arasındaki mevsim" },
    { name: "Bahri", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Denizle ilgili" },
    { name: "Banu", gender: "Kız", origin: "Farsça", syllables: 2, length: 4, meaning: "Prenses, hanımefendi" },
    { name: "Baran", gender: "Erkek", origin: "Farsça", syllables: 2, length: 5, meaning: "Yağmur, mevsim" },
    { name: "Barış", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Sulh, uyum" },
    { name: "Barkın", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Gezgin, seyyah" },
    { name: "Başak", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ekinlerin taneli başı" },
    { name: "Batuhan", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 7, meaning: "Güçlü hükümdar" },
    { name: "Begüm", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Hanımefendi, prenses" },
    { name: "Belinay", gender: "Kız", origin: "Türkçe", syllables: 3, length: 7, meaning: "Ayın göle yansıması" },
    { name: "Berat", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Günahlardan arındırma" },
    { name: "Beren", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Güçlü, kuvvetli" },
    { name: "Beril", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Değerli yeşil taş" },
    { name: "Berivan", gender: "Kız", origin: "Kürtçe", syllables: 3, length: 7, meaning: "Süt veren" },
    { name: "Berk", gender: "Erkek", origin: "Türkçe", syllables: 1, length: 4, meaning: "Sert, sağlam, güçlü" },
    { name: "Berkan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Sağlam kan" },
    { name: "Berkay", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Güçlü ve ay gibi parlak" },
    { name: "Berke", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Sağlam, dayanıklı" },
    { name: "Berra", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Doğru sözlü, hayır işleyen" },
    { name: "Betül", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Namuslu, temiz kadın" },
    { name: "Beyza", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Çok beyaz, lekesiz" },
    { name: "Bilge", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Çok bilen, alim" },
    { name: "Billur", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Kristal, cam" },
    { name: "Birce", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Tek, eşsiz yüce" },
    { name: "Birkan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Bir kan, kardeş" },
    { name: "Bora", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Şiddetli rüzgar" },
    { name: "Buğra", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Erkek deve" },
    { name: "Buket", gender: "Kız", origin: "Fransızca", syllables: 2, length: 5, meaning: "Çiçek demeti" },
    { name: "Burak", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Hz. Muhammed'in miraca çıkarken bindiği binek" },
    { name: "Burcu", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Güzel koku" },
    { name: "Burhan", gender: "Erkek", origin: "Arapça", syllables: 2, length: 6, meaning: "Delil, kanıt" },
    { name: "Buse", gender: "Kız", origin: "Farsça", syllables: 2, length: 4, meaning: "Öpücük" },
    { name: "Büşra", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Müjde, sevinçli haber" },

    // C
    { name: "Cahit", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Çalışkan, gayretli" },
    { name: "Can", gender: "Üniseks", origin: "Farsça", syllables: 1, length: 3, meaning: "Ruh, yaşam, sevgili" },
    { name: "Canan", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Sevgili, gönül verilen" },
    { name: "Canay", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Can ay" },
    { name: "Canberk", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 7, meaning: "Can gibi sağlam" },
    { name: "Caner", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Cana yakın er" },
    { name: "Cansu", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Yaşam suyu" },
    { name: "Celal", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Yücelik, ululuk" },
    { name: "Cem", gender: "Erkek", origin: "Farsça", syllables: 1, length: 3, meaning: "Hükümdar, şah" },
    { name: "Cemal", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Yüz güzelliği" },
    { name: "Cemre", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Ateş parçası, baharın habercisi" },
    { name: "Cenk", gender: "Erkek", origin: "Farsça", syllables: 1, length: 4, meaning: "Savaş, mücadele" },
    { name: "Ceren", gender: "Kız", origin: "Moğolca", syllables: 2, length: 5, meaning: "Ceylan, gazal" },
    { name: "Cevdet", gender: "Erkek", origin: "Arapça", syllables: 2, length: 6, meaning: "Cömertlik, iyilik" },
    { name: "Cevher", gender: "Erkek", origin: "Arapça", syllables: 2, length: 6, meaning: "Değerli taş, c" },
    { name: "Ceyda", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Uzun boylu ve güzel" },
    { name: "Ceyhun", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Orta Asya'da bir nehir" },
    { name: "Cihan", gender: "Erkek", origin: "Farsça", syllables: 2, length: 5, meaning: "Dünya, alem" },

    // Ç
    { name: "Çağan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Çağrılan, istenen" },
    { name: "Çağatay", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 7, meaning: "Bir Türk boyu" },
    { name: "Çağdaş", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Çağımızla ilgili" },
    { name: "Çağla", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Badem, kaysı gibi meyvelerin ham hali" },
    { name: "Çağlar", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Çağıldayarak akan su" },
    { name: "Çağrı", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Davet" },
    { name: "Çınar", gender: "Erkek", origin: "Farsça", syllables: 2, length: 5, meaning: "Uzun ömürlü, geniş yapraklı ağaç" },
    { name: "Çiğdem", gender: "Kız", origin: "Türkçe", syllables: 2, length: 6, meaning: "Kır bitkisi, çiçek" },

    // D
    { name: "Dağhan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Dağ gibi güçlü han" },
    { name: "Dalya", gender: "Kız", origin: "İbranice", syllables: 2, length: 5, meaning: "Asma dalı" },
    { name: "Damla", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Su tanesi" },
    { name: "Dani", gender: "Erkek", origin: "İbranice", syllables: 2, length: 4, meaning: "Tanrı benim hakimim" },
    { name: "Defne", gender: "Kız", origin: "Yunanca", syllables: 2, length: 5, meaning: "Güzel kokulu bir ağaç" },
    { name: "Demir", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Dayanıklı maden" },
    { name: "Deniz", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Büyük su kütlesi" },
    { name: "Deren", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Toplayan" },
    { name: "Derin", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Derin" },
    { name: "Derya", gender: "Üniseks", origin: "Farsça", syllables: 2, length: 5, meaning: "Deniz, okyanus" },
    { name: "Devrim", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 6, meaning: "Köklü değişim" },
    { name: "Dicle", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Bir nehir adı" },
    { name: "Didem", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Gözüm, gözüm gibi sevdiğim" },
    { name: "Dilara", gender: "Kız", origin: "Farsça", syllables: 3, length: 6, meaning: "Gönül alan, sevgili" },
    { name: "Dilşad", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Gönlü şad, mutlu" },
    { name: "Diyar", gender: "Erkek", origin: "Farsça", syllables: 2, length: 5, meaning: "Ülke, diyar" },
    { name: "Doğa", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 4, meaning: "Tabiat" },
    { name: "Doğu", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Güneşin doğduğu yön" },
    { name: "Doğukan", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 7, meaning: "Doğunun hükümdarı" },
    { name: "Doruk", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Dağın en yüksek noktası" },
    { name: "Duru", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Saf, berrak" },
    { name: "Duygu", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "His, hissetme" },

    // E
    { name: "Ebrar", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "İyiler, salihler" },
    { name: "Ece", gender: "Kız", origin: "Türkçe", syllables: 2, length: 3, meaning: "Kraliçe, güzel kadın" },
    { name: "Ecrin", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Allah'ın hediyesi" },
    { name: "Eda", gender: "Kız", origin: "Arapça", syllables: 2, length: 3, meaning: "Naz, cilve, tavır" },
    { name: "Ediz", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Yüksek" },
    { name: "Efe", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 3, meaning: "Yiğit, zeybek, ağabey" },
    { name: "Ege", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 3, meaning: "Bir deniz adı" },
    { name: "Egemen", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 6, meaning: "Bir yere hakim olan" },
    { name: "Ela", gender: "Kız", origin: "Farsça", syllables: 2, length: 3, meaning: "Sarıya çalan kestane rengi göz" },
    { name: "Elçin", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Halkın elçisi" },
    { name: "Elhancı", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 7, meaning: "El sanatları" },
    { name: "Elif", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Alfabenin ilk harfi, ince, narin" },
    { name: "Elmas", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Değerli taş" },
    { name: "Elnur", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Halkın nuru" },
    { name: "Emel", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Arzu, istek, umut" },
    { name: "Emin", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Güvenilir, korkusuz" },
    { name: "Emine", gender: "Kız", origin: "Arapça", syllables: 3, length: 5, meaning: "Güvenilir, inanılır kadın" },
    { name: "Emir", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Buyruk, komut, prens" },
    { name: "Emirhan", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 7, meaning: "Hükümdar, bey" },
    { name: "Emrah", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Arkadaş, dost" },
    { name: "Emre", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Aşık, dost, arkadaş" },
    { name: "Ender", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Çok az bulunan, nadir" },
    { name: "Enes", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "İnsan, dost" },
    { name: "Engin", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ucu bucağı görünmeyen, geniş" },
    { name: "Enise", gender: "Kız", origin: "Arapça", syllables: 3, length: 5, meaning: "Arkadaş, dost" },
    { name: "Enver", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Çok nurlu, çok parlak" },
    { name: "Eray", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Ay gibi parlak kimse" },
    { name: "Erbay", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ergin bey" },
    { name: "Ercan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Yiğit can" },
    { name: "Erdem", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Fazilet, yetenek" },
    { name: "Eren", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Ermiş, yetişmiş, cesur" },
    { name: "Ergün", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ergin gün" },
    { name: "Erhan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Yiğit han" },
    { name: "Erkan", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "İleri gelenler, büyükler" },
    { name: "Erkin", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Özgür" },
    { name: "Erol", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Er ol, yiğit ol" },
    { name: "Ertuğrul", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 8, meaning: "Yiğit tuğlu" },
    { name: "Esin", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "İlham, sabah rüzgarı" },
    { name: "Eslem", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Güvenli" },
    { name: "Esma", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "İsimler, adlar" },
    { name: "Esra", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "En çabuk, en hızlı" },
    { name: "Eylül", gender: "Kız", origin: "Süryanice", syllables: 2, length: 5, meaning: "Sonbaharın ilk ayı" },
    { name: "Ezgi", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Melodi, nağme" },

    // F
    { name: "Faik", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Üstün" },
    { name: "Fatih", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Fetheden, açan" },
    { name: "Fatma", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Sütten kesilmiş" },
    { name: "Fatoş", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Akıllı" },
    { name: "Fehmi", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Anlayış" },
    { name: "Ferhat", gender: "Erkek", origin: "Arapça", syllables: 2, length: 6, meaning: "Sevinç, neşe" },
    { name: "Feride", gender: "Kız", origin: "Arapça", syllables: 3, length: 6, meaning: "Eşi benzeri olmayan, tek" },
    { name: "Feyza", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Bolluk, bereket" },
    { name: "Fırat", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Geniş akan nehir" },
    { name: "Fikret", gender: "Erkek", origin: "Arapça", syllables: 2, length: 6, meaning: "Düşünce" },
    { name: "Filiz", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Bitkilerin yeni süren ucu" },
    { name: "Fuad", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Kalp, gönül" },
    { name: "Fulya", gender: "Kız", origin: "Yunanca", syllables: 2, length: 5, meaning: "Bir çiçek adı" },
    { name: "Funda", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Çalı, süpürge otu" },
    { name: "Furkan", gender: "Erkek", origin: "Arapça", syllables: 2, length: 6, meaning: "Hakkı batıldan ayıran" },

    // G
    { name: "Gamze", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Gülerken yanakta oluşan çukur" },
    { name: "Gaye", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Amaç, hedef" },
    { name: "Gediz", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Bir nehir adı" },
    { name: "Giray", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Kuvvetli" },
    { name: "Gizem", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Sır, bilinmeyen" },
    { name: "Gonca", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Açılmamış çiçek" },
    { name: "Gökay", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Gök gibi ay" },
    { name: "Gökçe", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Gökyüzü gibi mavi, güzel" },
    { name: "Gökhan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Göklerin hükümdarı" },
    { name: "Göksu", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Gök mavisi su" },
    { name: "Göktuğ", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Gök tuğu" },
    { name: "Gözde", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Çok sevilen, beğenilen" },
    { name: "Gül", gender: "Kız", origin: "Farsça", syllables: 1, length: 3, meaning: "Çiçek" },
    { name: "Gülay", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Gül gibi ay" },
    { name: "Gülbahar", gender: "Kız", origin: "Farsça", syllables: 3, length: 8, meaning: "Gül baharı" },
    { name: "Gülben", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Ben gülüm anlamında" },
    { name: "Gülçin", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Gül toplayan" },
    { name: "Gülden", gender: "Kız", origin: "Türkçe", syllables: 2, length: 6, meaning: "Gülden yapılmış" },
    { name: "Gülnaz", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Gül gibi nazlı" },
    { name: "Gülnur", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Gül nuru" },
    { name: "Gülşah", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Güllerin şahı" },
    { name: "Gülşen", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Gül bahçesi" },
    { name: "Günay", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Güneş - ay" },
    { name: "Güneş", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Gezegenimize ısı ve ışık veren gök cismi" },
    { name: "Gürbüz", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Sağlıklı, dinç" },
    { name: "Gürkan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Güçlü kan" },
    { name: "Gürsel", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Güçlü sel" },
    { name: "Güven", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "İnanma, bağlanma duygusu" },

    // H
    { name: "Hakan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Eski Türk hükümdarlarına verilen unvan" },
    { name: "Halil", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Sadık dost" },
    { name: "Halit", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Ebedi, ölümsüz" },
    { name: "Haluk", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "İyi huylu, geçimli" },
    { name: "Hamza", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Aslan" },
    { name: "Hande", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Gülüş, gülme" },
    { name: "Harun", gender: "Erkek", origin: "İbranice", syllables: 2, length: 5, meaning: "Peygamber adı" },
    { name: "Hasan", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Güzellik, iyilik" },
    { name: "Hatice", gender: "Kız", origin: "Arapça", syllables: 3, length: 6, meaning: "Erken doğan kız çocuğu" },
    { name: "Havva", gender: "Kız", origin: "İbranice", syllables: 2, length: 5, meaning: "İlk kadın" },
    { name: "Hayat", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Yaşam, ömür" },
    { name: "Hayriye", gender: "Kız", origin: "Arapça", syllables: 3, length: 7, meaning: "Hayırlı" },
    { name: "Hazal", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Kurumuş ağaç yaprağı" },
    { name: "Hazan", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Sonbahar" },
    { name: "Hazar", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Bin, deniz" },
    { name: "Helin", gender: "Kız", origin: "Yunanca", syllables: 2, length: 5, meaning: "Ateş, güneş" },
    { name: "Hilal", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Yeni ay" },
    { name: "Hilmi", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Yumuşak huylu" },
    { name: "Hulusi", gender: "Erkek", origin: "Arapça", syllables: 3, length: 6, meaning: "Temiz, saf" },
    { name: "Hülya", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Hayal, kuruntu" },
    { name: "Hümeyra", gender: "Kız", origin: "Arapça", syllables: 3, length: 7, meaning: "Kızıl" },
    { name: "Hüseyin", gender: "Erkek", origin: "Arapça", syllables: 3, length: 7, meaning: "Küçük güzel" },

    // I
    { name: "Ilgın", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Hafif esinti, bir ağaç türü" },
    { name: "Irmak", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Akarsu, nehir" },
    { name: "Işık", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 4, meaning: "Işın, aydınlık, nur" },
    { name: "Işıl", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Parlaklık, aydınlık" },
    { name: "Işılay", gender: "Kız", origin: "Türkçe", syllables: 3, length: 6, meaning: "Işık gibi parlak ay" },
    { name: "Işın", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Işığın çizgisi" },
    { name: "Işınsu", gender: "Kız", origin: "Türkçe", syllables: 3, length: 6, meaning: "Işık gibi berrak su" },

    // İ
    { name: "İbrahim", gender: "Erkek", origin: "İbranice", syllables: 3, length: 7, meaning: "İnananların babası" },
    { name: "İclal", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Yücelik, ululuk" },
    { name: "İdil", gender: "Kız", origin: "Fransızca", syllables: 2, length: 4, meaning: "Kır hayatını anlatan şiir" },
    { name: "İhsan", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "İyilik, lütuf" },
    { name: "İkbal", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Talih, baht, mutluluk" },
    { name: "İkram", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Saygı gösterme, ikramda bulunma" },
    { name: "İlay", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Su perisi, ay ışığı" },
    { name: "İlayda", gender: "Kız", origin: "Türkçe", syllables: 3, length: 6, meaning: "Su perisi" },
    { name: "İlhan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Hükümdar, imparator" },
    { name: "İlkay", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ayın ilk hali" },
    { name: "İlker", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "İlk doğan erkek çocuk" },
    { name: "İlkkan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "İlk doğan hükümdar" },
    { name: "İlknur", gender: "Kız", origin: "Türkçe", syllables: 2, length: 6, meaning: "İlk ışık" },
    { name: "İlksen", gender: "Kız", origin: "Türkçe", syllables: 2, length: 6, meaning: "İlk mutluluk" },
    { name: "İlter", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ülke yöneten" },
    { name: "İlteriş", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 7, meaning: "Ülkeyi toplayan" },
    { name: "İlyas", gender: "Erkek", origin: "İbranice", syllables: 2, length: 5, meaning: "Peygamber adı" },
    { name: "İman", gender: "Üniseks", origin: "Arapça", syllables: 2, length: 4, meaning: "İnanç, itikat" },
    { name: "İmge", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "İmaj, hayal" },
    { name: "İmran", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Bayındırlık, imar" },
    { name: "İnci", gender: "Kız", origin: "Çince", syllables: 2, length: 4, meaning: "İstiridyeden çıkan değerli süs tanesi" },
    { name: "İpek", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Zarif, kibar, yumuşak kumaş" },
    { name: "İrem", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Cennet bahçesi" },
    { name: "İrfan", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Bilgi, hikmet" },
    { name: "İsa", gender: "Erkek", origin: "İbranice", syllables: 2, length: 3, meaning: "Bir peygamber adı" },
    { name: "İsmail", gender: "Erkek", origin: "İbranice", syllables: 3, length: 6, meaning: "Tanrı'yı işiten" },
    { name: "İsmet", gender: "Üniseks", origin: "Arapça", syllables: 2, length: 5, meaning: "Kusursuzluk, temizlik" },
    { name: "İsra", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Gece yolculuğu" },
    { name: "İzel", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Sonsuzluk, ebedilik" },
    { name: "İzzet", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Onur, şeref" },

    // K
    { name: "Kaan", gender: "Erkek", origin: "Türkçe", syllables: 1, length: 4, meaning: "Hükümdar, Hanların Hanı" },
    { name: "Kader", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Alın yazısı" },
    { name: "Kadir", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Değerli, kıymetli, güçlü" },
    { name: "Kemal", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Olgunluk, yetkinlik" },
    { name: "Kenan", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Toprak" },
    { name: "Kerem", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Cömertlik, soyluluk" },
    { name: "Kerim", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Cömert, ulu" },
    { name: "Kıvanç", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Övünç, sevinç" },
    { name: "Koray", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ateşli, canlı, hareketli" },
    { name: "Kubilay", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 7, meaning: "Ünlü bir Türk hükümdarı" },
    { name: "Kuzey", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Bir yön" },
    { name: "Kübra", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "En büyük, çok büyük" },

    // L
    { name: "Lale", gender: "Kız", origin: "Farsça", syllables: 2, length: 4, meaning: "Bir çiçek adı" },
    { name: "Lamia", gender: "Kız", origin: "Arapça", syllables: 3, length: 5, meaning: "Parlak, parlayan" },
    { name: "Lara", gender: "Kız", origin: "Latince", syllables: 2, length: 4, meaning: "Koruyucu" },
    { name: "Leman", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Parlak" },
    { name: "Levent", gender: "Erkek", origin: "Farsça", syllables: 2, length: 6, meaning: "Boylu poslu, yakışıklı" },
    { name: "Leyla", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Gece, siyah saçlı güzel" },

    // M
    { name: "Mehmet", gender: "Erkek", origin: "Arapça", syllables: 2, length: 6, meaning: "Muhammed isminin Türkçeleşmiş hali" },
    { name: "Melda", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "İnce ve taze vücutlu" },
    { name: "Melek", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Allah'ın nurundan yaratılan varlık" },
    { name: "Melih", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Güzel, şirin" },
    { name: "Melike", gender: "Kız", origin: "Arapça", syllables: 3, length: 6, meaning: "Kadın hükümdar" },
    { name: "Melis", gender: "Kız", origin: "Yunanca", syllables: 2, length: 5, meaning: "Bal arısı" },
    { name: "Meltem", gender: "Kız", origin: "Türkçe", syllables: 2, length: 6, meaning: "Yazın karadan denize esen rüzgar" },
    { name: "Mert", gender: "Erkek", origin: "Farsça", syllables: 1, length: 4, meaning: "Sözünün eri, yiğit" },
    { name: "Merve", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Mekke'de bir dağ adı" },
    { name: "Metin", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Sağlam, dayanıklı" },
    { name: "Mine", gender: "Kız", origin: "Farsça", syllables: 2, length: 4, meaning: "İnce ve parlak nakış" },
    { name: "Mira", gender: "Kız", origin: "Latince", syllables: 2, length: 4, meaning: "Harika" },
    { name: "Miraç", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Yükselme, göğe çıkma" },
    { name: "Miray", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ay gibi parlak" },
    { name: "Murat", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "İstek, arzu, amaç" },
    { name: "Mustafa", gender: "Erkek", origin: "Arapça", syllables: 3, length: 7, meaning: "Seçilmiş, güzide" },
    { name: "Müge", gender: "Kız", origin: "Fransızca", syllables: 2, length: 4, meaning: "İnci çiçeği" },

    // N
    { name: "Nalan", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "İnleyen, feryat eden" },
    { name: "Naz", gender: "Kız", origin: "Farsça", syllables: 1, length: 3, meaning: "Kendini beğendirmek için yapılan davranış" },
    { name: "Nazan", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Nazlı, cilveli" },
    { name: "Nazlı", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Naz yapan, cilveli" },
    { name: "Nehir", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Irmak, büyük akarsu" },
    { name: "Nergis", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Bir çiçek adı" },
    { name: "Neslihan", gender: "Kız", origin: "Türkçe", syllables: 3, length: 8, meaning: "Han soyundan gelen" },
    { name: "Neşe", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Sevinç, keyif" },
    { name: "Neva", gender: "Kız", origin: "Farsça", syllables: 2, length: 4, meaning: "Melodi, nağme" },
    { name: "Nihat", gender: "Erkek", origin: "Farsça", syllables: 2, length: 5, meaning: "Tabiat, huy" },
    { name: "Nil", gender: "Kız", origin: "Sanskritçe", syllables: 1, length: 3, meaning: "Mısır'daki büyük nehir, mavi" },
    { name: "Nilay", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ayın parlaklığı" },
    { name: "Nisa", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Kadınlar" },
    { name: "Nur", gender: "Kız", origin: "Arapça", syllables: 1, length: 3, meaning: "Işık, parıltı" },

    // O
    { name: "Oğuz", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Doğru, sağlam, güçlü" },
    { name: "Oğuzhan", gender: "Erkek", origin: "Türkçe", syllables: 3, length: 7, meaning: "Oğuzların hükümdarı" },
    { name: "Okan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Anlayışlı, öğrenen" },
    { name: "Oktay", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Ok gibi güçlü ve ay gibi parlak" },
    { name: "Onur", gender: "Erkek", origin: "Fransızca", syllables: 2, length: 4, meaning: "Şeref, haysiyet" },
    { name: "Orhan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Şehrin hakimi" },
    { name: "Osman", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Bir kuş türü, ejderha" },
    { name: "Ozan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Şair, halk şairi" },

    // Ö
    { name: "Ömer", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Yaşama, ömür sürme" },
    { name: "Öykü", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Hikaye, masal" },
    { name: "Özge", gender: "Kız", origin: "Türkçe", syllables: 2, length: 4, meaning: "Başka, yabancı, güzel" },
    { name: "Özgür", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 5, meaning: "Hür, bağımsız" },
    { name: "Özkan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Soylu kan" },
    { name: "Özlem", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Hasret çekme" },

    // P
    { name: "Pamir", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Orta Asya'da bir yayla" },
    { name: "Pelin", gender: "Kız", origin: "Yunanca", syllables: 2, length: 5, meaning: "Acı ve güzel kokulu bir bitki" },
    { name: "Pınar", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Su kaynağı" },
    { name: "Polat", gender: "Erkek", origin: "Farsça", syllables: 2, length: 5, meaning: "Çelik, güç, kuvvet" },
    { name: "Poyraz", gender: "Erkek", origin: "Yunanca", syllables: 2, length: 6, meaning: "Kuzeydoğudan esen rüzgar" },

    // R
    { name: "Rabia", gender: "Kız", origin: "Arapça", syllables: 3, length: 5, meaning: "Dördüncü" },
    { name: "Ramazan", gender: "Erkek", origin: "Arapça", syllables: 3, length: 7, meaning: "Oruç ayı" },
    { name: "Rana", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Güzel, hoş görünen" },
    { name: "Recep", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Heybetli, saygıdeğer" },
    { name: "Rüya", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Düş" },
    { name: "Rüzgar", gender: "Üniseks", origin: "Farsça", syllables: 2, length: 6, meaning: "Yel, esinti" },

    // S
    { name: "Saadet", gender: "Kız", origin: "Arapça", syllables: 3, length: 6, meaning: "Mutluluk" },
    { name: "Sabri", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Sabırlı olan" },
    { name: "Sadık", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Doğru, gerçek dost" },
    { name: "Salih", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Elverişli, iyi, dindar" },
    { name: "Samet", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Sonsuz, ebedi" },
    { name: "Sarp", gender: "Erkek", origin: "Türkçe", syllables: 1, length: 4, meaning: "Dik, çıkılması zor" },
    { name: "Seda", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Ses, yankı" },
    { name: "Sedat", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Doğruluk, haklılık" },
    { name: "Selin", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Gür akan su" },
    { name: "Selma", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Barış içinde, huzurlu" },
    { name: "Semih", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Cömert, eli açık" },
    { name: "Sena", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Övgü, şimşek parıltısı" },
    { name: "Serdar", gender: "Erkek", origin: "Farsça", syllables: 2, length: 6, meaning: "Asker başı, komutan" },
    { name: "Serhat", gender: "Erkek", origin: "Arapça", syllables: 2, length: 6, meaning: "Sınır boyu" },
    { name: "Serkan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Soylu kan, başkan" },
    { name: "Serpil", gender: "Kız", origin: "Türkçe", syllables: 2, length: 6, meaning: "Geliş, büyü" },
    { name: "Sevgi", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Aşk, muhabbet" },
    { name: "Sevil", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Her zaman sevilen ol" },
    { name: "Sevim", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Hoşluk, şirinlik" },
    { name: "Sibel", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Buğday başağı, yağmur damlası" },
    { name: "Sinan", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Mızrak ucu" },
    { name: "Sinem", gender: "Kız", origin: "Farsça", syllables: 2, length: 5, meaning: "Gönlüm, yüreğim" },
    { name: "Su", gender: "Kız", origin: "Türkçe", syllables: 1, length: 2, meaning: "Yaşam kaynağı" },
    { name: "Sude", gender: "Kız", origin: "Farsça", syllables: 2, length: 4, meaning: "Sürmeli, boyalı" },
    { name: "Sultan", gender: "Kız", origin: "Arapça", syllables: 2, length: 6, meaning: "Hükümdar eşi" },
    { name: "Süleyman", gender: "Erkek", origin: "İbranice", syllables: 3, length: 8, meaning: "Huzur, barış" },

    // Ş
    { name: "Şebnem", gender: "Kız", origin: "Farsça", syllables: 2, length: 6, meaning: "Çiy, gece nemi" },
    { name: "Şevval", gender: "Kız", origin: "Arapça", syllables: 2, length: 6, meaning: "Hicri takvimin onuncu ayı" },
    { name: "Şeyma", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Vücudunda ben olan" },
    { name: "Şule", gender: "Kız", origin: "Arapça", syllables: 2, length: 4, meaning: "Alev, ateş" },

    // T
    { name: "Taha", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Kuran suresi" },
    { name: "Taner", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Şafak gibi aydınlık kimse" },
    { name: "Tarık", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Sabah yıldızı" },
    { name: "Tayfun", gender: "Erkek", origin: "Çince", syllables: 2, length: 6, meaning: "Büyük okyanus fırtınası" },
    { name: "Taylan", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Uzun boylu, yakışıklı" },
    { name: "Tolga", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Savaş başlığı, miğfer" },
    { name: "Toprak", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 6, meaning: "Yer kabuğunun yüzeyi" },
    { name: "Tuğba", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Cennet ağacı" },
    { name: "Tuğçe", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Küçük tuğ, kraliçe tacı" },
    { name: "Tuna", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Görkemli, gösterişli" },
    { name: "Tuncay", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Tunç gibi sağlam ay" },
    { name: "Tutku", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "İçten gelen istek" },
    { name: "Türkan", gender: "Kız", origin: "Türkçe", syllables: 2, length: 6, meaning: "Kraliçe, güzel kız" },

    // U
    { name: "Ufuk", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Gökyüzü ile yeryüzünün birleştiği çizgi" },
    { name: "Uğur", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Şans, talih" },
    { name: "Umut", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 4, meaning: "Ümit edilen şey" },
    { name: "Uras", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Büyük, ulu" },
    { name: "Utku", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 4, meaning: "Zafer, üstünlük" },
    { name: "Uzay", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 4, meaning: "Sonsuz boşluk" },

    // Ü
    { name: "Ümit", gender: "Üniseks", origin: "Farsça", syllables: 2, length: 4, meaning: "Umut" },

    // V
    { name: "Vedat", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Sevgi, dostluk" },
    { name: "Volkan", gender: "Erkek", origin: "İtalyanca", syllables: 2, length: 6, meaning: "Yanardağ" },

    // Y
    { name: "Yağız", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Esmer, yiğit" },
    { name: "Yağmur", gender: "Üniseks", origin: "Türkçe", syllables: 2, length: 6, meaning: "Gökten düşen su damlaları" },
    { name: "Yakup", gender: "Erkek", origin: "İbranice", syllables: 2, length: 5, meaning: "Takip eden, izleyen" },
    { name: "Yalçın", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 6, meaning: "Dik, sarp" },
    { name: "Yaman", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Güçlü, becerikli" },
    { name: "Yasemin", gender: "Kız", origin: "Farsça", syllables: 3, length: 7, meaning: "Güzel kokulu bir çiçek" },
    { name: "Yasin", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Kuran'da bir sure" },
    { name: "Yavuz", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Güçlü, çetin, sert" },
    { name: "Yeliz", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Güzel, havadar" },
    { name: "Yeşim", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Yeşil renkli değerli taş" },
    { name: "Yiğit", gender: "Erkek", origin: "Türkçe", syllables: 2, length: 5, meaning: "Güçlü, yürekli kahraman" },
    { name: "Yonca", gender: "Kız", origin: "Türkçe", syllables: 2, length: 5, meaning: "Şans getirdiğine inanılan bitki" },
    { name: "Yunus", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Bir peygamber adı, balık" },
    { name: "Yusuf", gender: "Erkek", origin: "İbranice", syllables: 2, length: 5, meaning: "İnleyen, ah eden" },

    // Z
    { name: "Zafer", gender: "Erkek", origin: "Arapça", syllables: 2, length: 5, meaning: "Amaca ulaşma, başarı" },
    { name: "Zehra", gender: "Kız", origin: "Arapça", syllables: 2, length: 5, meaning: "Yüzü pek beyaz ve parlak olan" },
    { name: "Zeki", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Akıllı, kavrayışlı" },
    { name: "Zeynep", gender: "Kız", origin: "Arapça", syllables: 2, length: 6, meaning: "Değerli taş, mücevher" },
    { name: "Ziya", gender: "Erkek", origin: "Arapça", syllables: 2, length: 4, meaning: "Işık, aydınlık" }
];
